# ==================================================
# ✅ Basic Site Info
# ==================================================
title: "Liu Yichuan"
name: "Liu Yichuan"
description: "Business Analytics @ NUS | AI x Finance | Portfolio & Projects"
url: "https://lydia372.github.io"
baseurl: ""  # 留空代表部署在根目录

# ==================================================
# ✅ Sidebar Profile Info (左边栏内容)
# ==================================================
author:
  avatar: "profile.png"
  name: "Liu Yichuan"
  bio: "Business Analytics student at NUS"
  location: "Singapore"
  employer: "National University of Singapore"
  email: "yichuan025@gmail.com"
  github: "lydia372"
  linkedin: "liu-yichuan"  # ⚠️改成你真实的 LinkedIn ID


# ==================================================
# ✅ Navigation Bar 顶部导航栏页面（顺序可调）
# ==================================================
header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/experience.md
  - _pages/cv.md

# ==================================================
# ✅ Markdown 设置 + 页面布局
# ==================================================
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# ==================================================
# ✅ 插件（建议保留 RSS Feed 和 sitemap）
# ==================================================
plugins:
  - jekyll-feed
  - jekyll-sitemap

# ==================================================
# ✅ 输出设置（文章链接结构）
# ==================================================
permalink: /:categories/:title/
timezone: Asia/Singapore