# Basic Site Info
title: "Liu Yichuan"
name: "Liu Yichuan"
description: "Business Analytics @ NUS | AI x Finance | Portfolio & Projects"
url: "https://lydia372.github.io"
baseurl: ""  # 留空表示网站部署在根目录

# Sidebar Profile Info
author:
  avatar: "profile.png"
  name: "Liu Yichuan"
  bio: "Business Analytics student at NUS"
  location: "Singapore"
  email: "yichuan025@gmail.com"
  linkedin: "your-linkedin-id"   # 如果没有可以删掉或留空

# Navigation Bar
header_pages:
  - about.md
  - projects.md
  - experience.md
  - cv.md

# Markdown + Layout
markdown: kramdown
highlighter: rouge

# Default Layout Settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins (推荐保留 RSS 和 sitemap)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalink format
permalink: /:categories/:title/
timezone: Asia/Singapore